### ISSUE TITLE
Guidance on how to use R-devel with RStudio

### ISSUE THREAD

**Issue by hturner** [r-devel/rdevguide#128]
> In windows I do not make any mention to Rstudio, perhaps I can add a mention that users should go and select which version of R want to use? (While for Linux users I could mention the RSTUIDO_WHICH_R variable to control that).
_original comment by @llrs on #124 _

I think this would be helpful as a common setup - potentially instructions for other IDEs could be contributed.

**Comment by bettinagruen** [comment]
I suppose that's a typo and

RSTUIDO_WHICH_R 

should rather read

RSTUDIO_WHICH_R 

?

**Comment by llrs** [comment]
Yes, my bad. The right variable to control for which R version Rstudio uses is the later. Thanks for catching it!
