### ISSUE TITLE
Separate subsection on getting an account on Bugzilla

### ISSUE THREAD

**Issue by hturner** [r-devel/rdevguide#136]
The information on how to get a Bugzilla account is buried deep in the Bug Tracking chapter, in a section on How to report a bug (https://contributor.r-project.org/rdevguide/BugTrack.html#RCorePkgBug). 

I often want to point people to this specific information and not always in the context of reporting a bug (they may want to add a comment to an existing bug that they are reviewing, or suggest a new feature). 

So it would be helpful to have this information in its own subsection. This might be done in a short chapter introducing Bugzilla, so we would have:

Bug Tracking (intro to Bugzilla, some info on Navigating Bugzilla from Bug Reviewing chapter)
Reporting Bugs (most of content from existing Bug Tracking chapter)
Reviewing Bugs

**Comment by SaranjeetKaur** [comment]
This issue is partially addressed through the PRs #147 and #146.

**Comment by SaranjeetKaur** [comment]
Remaining part of this issue is addressed through PR #147
