### ISSUE TITLE
link to github source from guide

### ISSUE THREAD

**Issue by shannonpileggi** [r-devel/rdevguide#176]
Hi! When looking at the guide I do not see a link to the github repository that hosts the guide, to make it it quicker to file issues and such. Is it there and I missed it? If not, this would be a handy feature.

**Comment by llrs** [comment]
Yes, I realize this also recently when suggesting to open issues to provide feedback to the guide. 
I'll try to add them today, as It is only [adding some few lines](https://github.com/OSCA-source/OSCA.basic/blob/5e697e8d105e2e30879264057f110bef495a1f9e/inst/book/_output.yml#L12-L14).

**Comment by shannonpileggi** [comment]
Hi @llrs! I actually still do not see the gh link from the book. Where do you see it?

**Comment by llrs** [comment]
On the top left corner, the forth icon leads to edit the book. 
![Screenshot of the book top left corner from 2024-07-23 01-24-31](https://github.com/user-attachments/assets/77b58a8f-d4f6-4c9c-857e-38e76bf68e6d)
I thought this might be enough but it might require to add a different option to simply show the github icon:

```
bookdown::gitbook:
  config:
    sharing:
      github: yes
```

**Comment by llrs** [comment]
Now it does show the github icon at the top right corner.

**Comment by shannonpileggi** [comment]
Amazing, looks great!! Thank you!
