### ISSUE TITLE
explicit patch submission instructions

### ISSUE THREAD

**Issue by shannonpileggi** [r-devel/rdevguide#177]
Recently at R Dev Day PLUS, Martin commented on how to submit the "perfect" patch. I see a related section in 7.4.1 & 7.6, but I don't think it as explicitly goes through all the steps regarding the attachment and such??

<https://github.com/r-devel/r-svn/pull/172#issuecomment-2228696800>

Appending `.diff` to the end of the [r-svn PR] URL automatically provides something you save from your browser as plain text file, named, e.g., `toTitleCase_PR-18674.diff` and then
in R's bugzilla, you'd typically use the Add an Attachment option to add that *.diff file as attachment:
- on the new Create New Attachment web page, add a Brief Decription ,
- also click the Content Type: patch box, and then
- add comments (often prose text) below rather than in the original bugzilla page for the PR.
- press Submit
This will give you a perfect bugzilla submission, with only one e-mail to all of R-core plus PR author and more listeners.

vs what was initially submitted:
<https://bugs.r-project.org/show_bug.cgi?id=18674>

fyi @sarahzeller @reikookamoto @Bisaloo

**Comment by llrs** [comment]
I think this is very useful and it would be great to add it to the book to annotate what was previously shared on individual cases.
Perhaps @SaranjeetKaur who originally wrote the section can provide more feedback (or add it to the book).

**Comment by SaranjeetKaur** [comment]
Thanks for the tag @llrs and agree with you that it would great to add this to the dev guide. 

@shannonpileggi - would you like to open a PR about the same?

**Comment by shannonpileggi** [comment]
Sure, will do! Thanks for the feedback!
