### ISSUE TITLE
R Developer's Guide visibility

### ISSUE THREAD

**Issue by perryrivera** [r-devel/rdevguide#22]
I'm unable to find the guide in my top links on Google.com

It might be helpful to submit whatever SEO or whatever is necessary so that the link:
https://forwards.github.io/rdevguide/

show's up high on Google.com's rank list.

Hope that helps! 

-Perry Rivera

**Comment by hturner** [comment]
It has helped significantly to move to the r-project.org domain: now searching "R development guide" brings the guide up top. Similarly a search for "contributing to r" brings the Contributor site up top. This has a link to the guide in the navigation bar and I've just added a link on the home page as well. 

So this helps with visibility. @SaranjeetKaur will also be adding a cover page which should improve visibility on bookdown.org, so I'll leave this issue open until that is done.

**Comment by hturner** [comment]
We have a separate issue for the cover page (#86), so closing this one.
