### ISSUE TITLE
"Building R and R packages" section needs updated to reflect the changes with Rtools42

### ISSUE THREAD

**Issue by yutannihilation** [r-devel/rdevguide#29]
I was trying to contribute to R-devel by following the guide, but it turned out we cannot use `r-windows/r-base` for R >=4.2.

https://github.com/r-windows/r-base/pull/34#issuecomment-1001213439

I'm really hoping the situation will be improved, so I have no idea how the guide should be updated at the moment.

**Comment by mmaechler** [comment]
Yes, building R from the sources is currently (back to) be covered entirely by the [Writing R Extensions](https://cran.r-project.org/doc/manuals/R-exts.html) manual the [*source*](https://github.com/r-devel/r-svn/blob/master/doc/manual/R-exts.texi) of which is part of the R sources, hence maintained by R core.
The Rtools42 being relatively new, it can well have things missing, or not easy enough to understand.  For the time being, the R-devel mailing list may be the best place to ask for clarifications.

**Comment by hturner** [comment]
Fixed by #74
