### ISSUE TITLE
update links to developer blog

### ISSUE THREAD

**Issue by hturner** [r-devel/rdevguide#30]
Was: https://developer.r-project.org/Blog/public/ (still works but doesn't redirect) 
Now: https://blog.r-project.org/

**Comment by SaranjeetKaur** [comment]
we might also want to include this link in the translations chapter: https://blog.r-project.org/2022/07/25/r-can-use-your-help-translating-r-messages/index.html

**Comment by SaranjeetKaur** [comment]
These links have been added to the issue about documenting weblate and will be taken care of in that chapter/section. Closing this issue now.

**Comment by hturner** [comment]
@Saranjeet Kaur can you still fix the existing links in the guide now. We should not have any links to https://developer.r-project.org/Blog/public/

**Comment by SaranjeetKaur** [comment]
This is updated and fixed now.
