### ISSUE TITLE
Add contributors using bot

### ISSUE THREAD

**Issue by SaranjeetKaur** [r-devel/rdevguide#35]
Adding all the contributors using the contributors bot.

**Comment by SaranjeetKaur** [comment]
@all-contributors please add @SaranjeetKaur for content

**Comment by SaranjeetKaur** [comment]
@all-contributors please add @hturner for content

**Comment by SaranjeetKaur** [comment]
@all-contributors please add @MayaGans for infra

**Comment by SaranjeetKaur** [comment]
@all-contributors please add @SaranjeetKaur for doc, ideas

**Comment by SaranjeetKaur** [comment]
@all-contributors please add @hturner for code, maintenance, mentoring, projectManagement, review

**Comment by SaranjeetKaur** [comment]
@all-contributors please add @willingc for review

**Comment by SaranjeetKaur** [comment]
@all-contributors please add @llrs for review

**Comment by SaranjeetKaur** [comment]
@all-contributors please add @bettinagruen for review

**Comment by SaranjeetKaur** [comment]
@all-contributors please add @mine-cetinkaya-rundel for review

**Comment by SaranjeetKaur** [comment]
@all-contributors please add @MichaelChirico for review, question

**Comment by SaranjeetKaur** [comment]
@all-contributors please add @hturner for fundingFinding, question, research

**Comment by SaranjeetKaur** [comment]
@all-contributors please add @hturner for fundingFinding, research

**Comment by SaranjeetKaur** [comment]
@all-contributors please add @SaranjeetKaur for fundingFinding, research

**Comment by SaranjeetKaur** [comment]
@all-contributors please add @hturner for eventOrganizing, talk

**Comment by SaranjeetKaur** [comment]
@all-contributors please add @SaranjeetKaur for eventOrganizing, talk, video

**Comment by hturner** [comment]
Hi Jonathan, You are receiving notifications because you are watching the repository on GitHub. You can stop this by using the unsubscribe link in the email from GitHub, or you can visit the repository (https://github.com/r-devel/rdevguide) and select the notification level you prefer in the Notifications menu (watch/unwatch button).

**Comment by SaranjeetKaur** [comment]
@all-contributors please add @HayesJohnD for review

**Comment by SaranjeetKaur** [comment]
Closing this to have more regular contributor's updates on the repo

**Comment by SaranjeetKaur** [comment]
add a HOWTO-acknowledge-contributors.md file
