### ISSUE TITLE
r-devel/r-svn Mirror: Contribution Docs: GIT Cheatsheet + GIT IDE

### ISSUE THREAD

**Issue by jtelleriar** [r-devel/rdevguide#64]
For r-devel/r-svn SVN mirror:
https://github.com/r-devel/r-svn

Find attached an easy to use GIT Cheatsheet:
https://about.gitlab.com/images/press/git-cheat-sheet.pdf

And an easy to use GIT IDE, free for Open Source/Public Projects:
https://www.gitkraken.com/

**Comment by hturner** [comment]
@llrs something to consider when working on the sections about installing R from source and about the git workflow.

**Comment by hturner** [comment]
The uses of git covered by the guide (forking git mirror to test contributions, or contributing to the guide itself) do not  require people to be familiar with the git commands or to use a particular IDE. We have documented browser-based workflows suitable for people unfamiliar with git. Linking to more general documentation may confuse things more!
