### ISSUE TITLE
Create an image of a book cover

### ISSUE THREAD

**Issue by SaranjeetKaur** [r-devel/rdevguide#85]
I think you need to create an image of a book cover using the R logo as the main image. See for example the images on https://bookdown.org/ - they are the cover image of the hard copy book. We don't have a hard copy book of course, but you could create a cover page as a PDF to use as an image (e.g. with PDF export from Word or some other program) . Actually the image for "R Programming for Data Science" looks like a self-made example. So you just need the title, the image and R Contribution Working Group as the author.

Consider how it will look on Twitter, e.g. https://twitter.com/straightedge/status/1203515396910772230?s=20&t=3ApdM_TKev1KPzMP3IW7WA - either make the whole image square or center the image vertically on a larger page so that only the R logo shows on the Twitter image.

_Originally posted by @hturner in https://github.com/r-devel/rdevguide/pull/71#discussion_r982459584_

**Comment by hturner** [comment]
We can now see what the existing image looks like on https://bookdown.org/home/archive/ - not that great! I think at the same time as creating the book cover we should improve the description that appears alongside it. At the moment we just have a single sentence, which does not make it clear that the guide is about contributing to the development of R itself.
