### ISSUE TITLE
Cover image for PDF and EPUB

### ISSUE THREAD

**Issue by SaranjeetKaur** [r-devel/rdevguide#86]
You need to also consider how to add the cover image to the PDF and EPUB. There is some guidance on PDF here: https://stackoverflow.com/a/43057244/173755. It may be easiest to do this first, then split the first page off the compiled PDF to use as `cover-image` in the YAML for the HTML and EPUB versions.  

Note that eventually we want to replace the index with more helpful content for people visiting the guide for the first time. I'm not sure yet if that will be your new Getting Started/Introduction page, or a much shorter version. I'm also not sure if the Acknowledgements should be at the end of this, or elsewhere in the book. It would be good to look at what other people have done to get an idea of good practice. Maybe something like https://www.tidytextmining.com/ with a short welcome explaining what the guide is about and a separate preface ending in acknowledgements? Probably call it something other than Preface though as people may think they can skip it. Getting Started is still good for that part I think.

_Originally posted by @hturner in https://github.com/r-devel/rdevguide/pull/71#pullrequestreview-1123798179_

**Comment by hturner** [comment]
Closed by #208
