### ISSUE TITLE
Clarity on exceptions in po directory

### ISSUE THREAD

**Issue by SaranjeetKaur** [r-devel/rdevguide#89]
Do these exceptions all refer to files contained in the po directory of the base package?

_Originally posted by @bettinagruen in https://github.com/r-devel/rdevguide/pull/63#discussion_r989766500_

**Comment by SaranjeetKaur** [comment]
@MichaelChirico - do you have any insights on this comment by Bettina?

**Comment by MichaelChirico** [comment]
Yes, the exception is only for base/po

**Comment by MichaelChirico** [comment]
Oh, whoops, I didn't realize I was committing to `main`... Closed in f955c18499f0914d06b6e4869671bcbc0d8487aa. Comments welcome for follow-up.
